# General Site Settings
logo: namoslogocls.svg

# Contact links
twitter: https://twitter.com/bossnayamoss
instagram: https://instagram.com/bossnayamoss 

# Newsletter
mailchimp: https://nayamoss.us3.list-manage.com/subscribe/post?u=349f607aae072db8a2d00769e&amp;id=d48b0efb2e